### ISSUE TITLE
sensor is not responding

### ISSUE THREAD

**Issue by gyan9427** [dthain/QMC5883L#14]
hi there,
 i used your library but the only thing i got was the message,
 "turn the sensor in all directions for calibration"
and when i turned nothing happened 
could you please help me with the issue???

**Comment by dthain** [comment]
Hello - Thanks for giving it a try.  It's hard to debug problems from a brief description, since the problem could be in the software, yes, but also in the hardware, or the circuit hookup, or the power supply, etc...  As a next step, I would suggest using compass.read_raw() to get and print the raw values from the magnetometer to see if any data is coming back.
