### ISSUE TITLE
I2C stops working at fast reading (100Hz) solved

### ISSUE THREAD

**Issue by Janzarik** [dthain/QMC5883L#17]
With this library I had issues to get a reliable connection to the sensor when I executed `readRaw()` command more than 50 times a second. Even though the Sensor could work up to 200Hz.

When reading the chapter "8.2.4 I2C Read" in the datasheet, i discovered, that for reading the sensor data (x,y,z) there should only be sent one Stop-Bit from the master.
I am assuming, that your library instead is sending two Stop-Bits for one data-reading sequence. As far as I understand the `Wire.h` library, the `Wire.endTransmission();` line is sending a Stop-Bit even though it shouldn't.

After I added a false `Wire.endTransmission(false);` in the read function, I could achieve a reliable 100Hz connection.

**Comment by dthain** [comment]
Hello @Janzarik and thanks for the update, glad that you got it working.

My understanding of endTransmission() is that (false) causes the master to hold on to the bus, rather than releasing it, so that it can quickly issue another command.  It makes sense that it would allow you to query at a higher rate.  But it might also interfere with the correct operation of other devices on the bus.

https://www.arduino.cc/reference/en/language/functions/communication/wire/endtransmission/

Just so I understand what's going on, does your test setup have any other I2C devices connected simultaneously?

**Comment by Janzarik** [comment]
Thank you for sharing the libary! Yes there is only one QMC5883 connected to the I2C bus.

I see. In the case of multiple sensors sharing one I2C bus, the default `Wire.endTransmission();` makes sence.

**Comment by Janzarik** [comment]
Update (just for the protocol): The issue was rather an electrical one. I was using a holybro M8 5883 GPS module, including the QMC5883L compass. I guess, that the 3,3V regulator on that module isn't powerful enough to supply GPS and compass at full performance at once. Playing around with different pull-up resistors didn't work either.

 When testing the library on another module (GY-271), there were no issues even at 100Hz poll rate and 400000Hz I2C clock. The GY-271 has its own 3,3V regulator and a logic level amplifier.

**Comment by dthain** [comment]
Ok, glad to hear it is working.
