### ISSUE TITLE
readHeading returns 1

### ISSUE THREAD

**Issue by Fasic** [dthain/QMC5883L#3]
readHeading is returning 1 allways! and you don't have pass by reference so just return heading; mybe? xD

and Wire.begin(sda, scl); call is missing? (for me, for nodemcu) so mybe adding this?

and include arduino.h is needed for atan2 to work (for me again). BTW thanks ALOTE! for code :+1:

**Comment by dthain** [comment]
Hello @Fasic, glad you find it useful.

I believe the portable fix to the `atan2` problem is to `#include <math.h>` in `QMC5883L.h`.  This is fixed in the latest release (1.0.2) and it works for me on Arduino 1.8.5 and also Teensyduino.  I don't have a nodemcu to test on.  Let me know if it works for you.

The library has no way of knowing if you are using non-standard pins for SDA and SCL, so if you need a custom `Wire.begin(sda,scl)` then that should go in your main program.

**Comment by dthain** [comment]
I believe this is fixed.
